/*
 * Note: this file originally auto-generated by mib2c using
 *        $
 */
#ifndef PGSTATBGWRITER_H
#define PGSTATBGWRITER_H

/* function declarations */
void init_pgstatBgWriter(void);
Netsnmp_Node_Handler handle_pgstatBgWriterCheckpointsTimed;
Netsnmp_Node_Handler handle_pgstatBgWriterCheckpointsRequested;
Netsnmp_Node_Handler handle_pgstatBgWriterBuffersCheckpoint;
Netsnmp_Node_Handler handle_pgstatBgWriterBuffersClean;
Netsnmp_Node_Handler handle_pgstatBgWriterMaxWrittenClean;
Netsnmp_Node_Handler handle_pgstatBgWriterBuffersBackend;
Netsnmp_Node_Handler handle_pgstatBgWriterBuffersAllocated;
void refreshNumbers(void);
void loadNumbersFromDB(void);

#endif /* PGSTATBGWRITER_H */
