/*
 * Note: this file originally auto-generated by mib2c using
 *        $
 */

#include <net-snmp/net-snmp-config.h>
#include <net-snmp/net-snmp-includes.h>
#include <net-snmp/agent/net-snmp-agent-includes.h>
#include "pgstatDatabaseTable.h"

/** Initialize the pgstatDatabaseTable table by defining its contents and how it's structured */
void
initialize_table_pgstatDatabaseTable(void)
{
    const oid pgstatDatabaseTable_oid[] = {1,3,6,1,4,1,27645,3,1};
    netsnmp_table_data_set *table_set;
    netsnmp_table_row *row;

    /* create the table structure itself */
    table_set = netsnmp_create_table_data_set("pgstatDatabaseTable");

    /* comment this out or delete if you don't support creation of new rows */
    //table_set->allow_creation = 1;

    /***************************************************
     * Adding indexes
     */
    DEBUGMSGTL(("initialize_table_pgstatDatabaseTable",
                "adding indexes to table pgstatDatabaseTable\n"));
    netsnmp_table_set_add_indexes(table_set,
                           ASN_INTEGER,  /* index: pgstatDatabaseIndex */
                           0);

    /*
     * set up what a row "should" look like, starting with the index 
     */
//    netsnmp_table_dataset_add_index(table_set, ASN_INTEGER);


    DEBUGMSGTL(("initialize_table_pgstatDatabaseTable",
                "adding column types to table pgstatDatabaseTable\n"));		 
    netsnmp_table_set_multi_add_default_row(table_set,
            COLUMN_PGSTATDATABASEINDEX, ASN_INTEGER, 0,
            NULL, 0,
            COLUMN_PGSTATDATABASENAME, ASN_OCTET_STR, 0,
            NULL, 0,
            COLUMN_PGSTATDATABASEBACKENDS, ASN_GAUGE, 0,
            NULL, 0,
            COLUMN_PGSTATDATABASECOMMITS, ASN_COUNTER, 0,
            NULL, 0,
            COLUMN_PGSTATDATABASEROLLBACKS, ASN_COUNTER, 0,
            NULL, 0,
            COLUMN_PGSTATDATABASEBLOCKSREAD, ASN_COUNTER, 0,
            NULL, 0,
            COLUMN_PGSTATDATABASEBLOCKSHIT, ASN_COUNTER, 0,
            NULL, 0,
            COLUMN_PGSTATDATABASETUPLESRETURNED, ASN_COUNTER, 0,
            NULL, 0,
            COLUMN_PGSTATDATABASETUPLESFETCHED, ASN_COUNTER, 0,
            NULL, 0,
            COLUMN_PGSTATDATABASETUPLESINSERTED, ASN_COUNTER, 0,
            NULL, 0,
            COLUMN_PGSTATDATABASETUPLESUPDATED, ASN_COUNTER, 0,
            NULL, 0,
            COLUMN_PGSTATDATABASETUPLESDELETED, ASN_COUNTER, 0,
            NULL, 0,
            COLUMN_PGSTATDATABASEROLLBACKRATIO, ASN_OPAQUE, 0,
            NULL, 0,
            COLUMN_PGSTATDATABASECACHEHITRATIO, ASN_OPAQUE, 0,
            NULL, 0,
            COLUMN_PGSTATDATABASETUPLESMODIFIED, ASN_COUNTER, 0,
            NULL, 0,
	      0);
    
    /* registering the table with the master agent */
    /* note: if you don't need a subhandler to deal with any aspects
       of the request, change pgstatDatabaseTable_handler to "NULL" */
    netsnmp_register_table_data_set(netsnmp_create_handler_registration("pgstatDatabaseTable", pgstatDatabaseTable_handler,
                                                        pgstatDatabaseTable_oid,
                                                        OID_LENGTH(pgstatDatabaseTable_oid),
                                                        HANDLER_CAN_RWRITE),
                            table_set, NULL);

    /*
     * create the a row for the table, add the data, and add the row to the table 
     */

    // FIXME: it just adds a single row indexed with 0...
    // FIXME: numeric values are all zeroed...
	/*
	$ snmpwalk localhost pgstatDatabaseTable
	PGSTAT-MIB::pgstatDatabaseName.0 = STRING: postgres
	PGSTAT-MIB::pgstatDatabaseBackends.0 = Gauge32: 0
	PGSTAT-MIB::pgstatDatabaseCommits.0 = Counter32: 0
	PGSTAT-MIB::pgstatDatabaseRollbacks.0 = Counter32: 0
	*/

    row = netsnmp_create_table_data_row();
    netsnmp_table_row_add_index(row, ASN_INTEGER, 15678, 0);
    netsnmp_set_row_column(row, COLUMN_PGSTATDATABASENAME, ASN_OCTET_STR, "postgres", strlen("postgres"));
    netsnmp_set_row_column(row, COLUMN_PGSTATDATABASEBACKENDS, ASN_GAUGE, 200, 0);
    netsnmp_set_row_column(row, COLUMN_PGSTATDATABASECOMMITS, ASN_COUNTER, 50000, 0);
    netsnmp_set_row_column(row, COLUMN_PGSTATDATABASEROLLBACKS, ASN_COUNTER, 50000, 0);
    netsnmp_set_row_column(row, COLUMN_PGSTATDATABASEROLLBACKRATIO, ASN_OPAQUE, 5, 0);
    netsnmp_table_dataset_add_row(table_set, row);

    row = netsnmp_create_table_data_row();
    netsnmp_table_row_add_index(row, ASN_INTEGER, 32871, 0);
    netsnmp_set_row_column(row, COLUMN_PGSTATDATABASENAME, ASN_OCTET_STR, "rodrigo", strlen("rodrigo"));
    netsnmp_set_row_column(row, COLUMN_PGSTATDATABASEBACKENDS, ASN_GAUGE, 150, 0);
    netsnmp_table_dataset_add_row(table_set, row);
}

/** Initializes the pgstatDatabaseTable module */
void
init_pgstatDatabaseTable(void)
{

  /* here we initialize all the tables we're planning on supporting */
    initialize_table_pgstatDatabaseTable();
}

/** handles requests for the pgstatDatabaseTable table, if anything else needs to be done */
int
pgstatDatabaseTable_handler(
    netsnmp_mib_handler               *handler,
    netsnmp_handler_registration      *reginfo,
    netsnmp_agent_request_info        *reqinfo,
    netsnmp_request_info              *requests) {
    /* perform anything here that you need to do.  The requests have
       already been processed by the master table_dataset handler, but
       this gives you chance to act on the request in some other way
       if need be. */
    return SNMP_ERR_NOERROR;
}
